"""Build README.md from the JSON each notebook wrote, then export every notebook to PDF.

Usage:
    python make_report.py            # README + PDFs
    python make_report.py --no-pdf   # README only
"""

from __future__ import annotations

import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")

NOTEBOOKS = [
    ("00_inventory", "Data inventory & integrity verification"),
    ("01_diabetes130", "Diabetes 130-US hospitals (tabular, MLP)"),
    ("02_mnist", "MNIST (image, CNN)"),
    ("03_cifar10", "CIFAR-10 (image, CNN)"),
    ("04_compare", "Comparison + improved CNN models"),
    ("06_mnist_lenet", "MNIST (image, LeNet-5)"),
    ("07_cifar10_lenet", "CIFAR-10 (image, LeNet-5)"),
]


def _load(name):
    p = os.path.join(RESULTS, name)
    if not os.path.exists(p):
        return None
    with open(p) as f:
        return json.load(f)


def _rows(payload, keys=("results", "full_results")):
    out = []
    for k in keys:
        out.extend(payload.get(k, []) if payload else [])
    return out


def _table(rows, cols, headers):
    lines = ["| " + " | ".join(headers) + " |",
             "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        cells = []
        for c in cols:
            v = r.get(c, "")
            if isinstance(v, float):
                v = f"{v:.4f}" if c != "train_seconds" else f"{v:.1f}"
            elif isinstance(v, int):
                v = f"{v:,}"
            cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def build_readme() -> str:
    d1, d2, d3 = _load("01_diabetes130.json"), _load("02_mnist.json"), _load("03_cifar10.json")
    d4 = _load("04_variants.json")
    d6, d7 = _load("06_mnist_lenet.json"), _load("07_cifar10_lenet.json")

    parts = []
    parts.append("""# Assignment 4 — Comparative Evaluation of CNN Architectures & Frameworks

A single learning task formulated through three distinct paradigms — **custom NumPy from scratch**, **TensorFlow/Keras**, and **PyTorch** — across three benchmark datasets, accompanied by a systematic architecture-evolution benchmark.

## Deliverables

| File | Contents |
|---|---|
| `pdf/FINAL_REPORT_A4_FULL.pdf` | **Comprehensive 172-Page Master Final Report** in Vietnamese, including Part I (Chapters 1-10 analysis), Part II (Appendices A-F embedding all executed notebooks with code & output cells), and Part III (Appendices G-H with core library code and glossary) — matching the 165-page standard of `A4_02_HungNguyenBa_120.pdf`. |
| `00_inventory.ipynb` | Data inventory & integrity verification across all three benchmark datasets |
| `01_diabetes130.ipynb` | Diabetes 130-US hospitals (tabular, 179 features, 3 classes) — MLP across all three framework legs |
| `02_mnist.ipynb` | MNIST (1x28x28 grayscale digits) — CNN across all three framework legs |
| `03_cifar10.ipynb` | CIFAR-10 (3x32x32 color objects) — CNN across all three framework legs |
| `04_compare.ipynb` | Cross-dataset comparison, lecture slide-28 component matrix, and the M1..M4 architecture-evolution benchmark |
| `06_mnist_lenet.ipynb` | MNIST re-evaluated with modernized **LeNet-5** (LeCun et al., 1998) across all three frameworks — parallel benchmark |
| `07_cifar10_lenet.ipynb` | CIFAR-10 evaluated with identical LeNet-5 architecture across all three frameworks |
| `ass4_utils.py` | Unified data loader, metrics calculation, timing, and model persistence — guarantees identical data splits |
| `scratch_nn.py` | Native NumPy deep learning engine: Conv2D/MaxPool2D/Dense/ReLU/Dropout with analytical backward passes, Adam, and finite-difference gradient verification |
| `variants.py` | Architectural evolution models M1..M4 implemented in PyTorch |
| `results/` | Machine-readable JSON run records and consolidated `all_runs.csv` |
| `results/models/` | Serialized model parameters per notebook (`.pt`, `.keras`, `.npz`) paired with metadata sidecars |
| `results/variant_cache/` | Checkpointed weights for M1..M4 variants — regenerated via `python prefill_variants.py` |

Execute notebooks sequentially; `04_compare.ipynb` aggregates experimental metrics generated by the preceding notebooks.

## Environment

- Python 3.11 / Anaconda Python on Windows, Jupyter execution kernel **`ass4`**
- PyTorch with CUDA hardware acceleration on an NVIDIA GeForce RTX 3060 GPU
- TensorFlow 2.21 / Keras 3.15 — **CPU execution**, reflecting standard Windows-native TensorFlow releases since 2.10

This architectural distinction is critical: PyTorch and Keras wall-clock times reflect different compute targets (GPU vs. CPU). Parameter totals, tensor shapes, and classification accuracies are directly comparable, whereas wall-clock timings capture hardware differences.

## The Fairness Rule

All experimental comparisons adhere strictly to the fairness standard established in lecture 04, slide 29:

> Same Dataset + Same Split + Same Architecture + Comparable Hyperparameters

All three implementation legs consume arrays from a centralized loader with synchronized seeds, ensuring byte-identical training and evaluation partitions.
""")

    # ---- results ----
    parts.append("\n## Results\n")
    for payload, title in ((d1, "Diabetes 130-US hospitals — MLP"),
                           (d2, "MNIST — CNN"),
                           (d3, "CIFAR-10 — CNN")):
        if not payload:
            continue
        rows = _rows(payload)
        parts.append(f"### {title}\n")
        parts.append(_table(
            rows,
            ["framework", "dataset", "n_params", "epochs", "train_seconds",
             "test_accuracy", "f1_macro"],
            ["Framework", "Dataset", "Params", "Epochs", "Train (s)", "Accuracy", "Macro F1"],
        ))
        parts.append("")

    if d4:
        parts.append("### Improved CNN Models (Tutorial Section 45, Full CIFAR-10)\n")
        parts.append(_table(
            d4["variants"],
            ["model", "n_params", "epochs", "train_seconds", "test_accuracy", "f1_macro"],
            ["Model", "Params", "Epochs", "Train (s)", "Accuracy", "Macro F1"],
        ))
        parts.append("""
Every architecture in this progression integrates exactly one additional mechanism:

- **M1** — Baseline convolutional backbone (`Conv + ReLU + MaxPool`)
- **M2** — `+ BatchNorm`, stabilizing intermediate activation distributions and curbing internal covariate shift
- **M3** — `+ Residual connections` ($Y = \\mathcal{F}(X) + X$), establishing unobstructed skip pathways for gradient backpropagation and signal propagation
- **M4** — `+ Squeeze-and-Excitation (SE) attention`, adaptively recalibrating cross-channel feature responses

**Incremental structural sophistication does not automatically ensure generalization.** Incorporating Batch Normalization produced the single most decisive performance surge (+5.31% accuracy, rising from 69.55% to 74.86%) at an almost negligible cost of 224 parameters. Adding residual skip connections contributed an extra +0.88% boost (reaching 75.74%); across a shallow three-stage depth, signal degradation remains minimal. Most instructively, channel-wise attention failed to deliver test gains: M4 slightly trailed M3 by -0.49% (75.25% vs. 75.74%) despite achieving the lowest empirical training loss (0.4335), serving as a textbook illustration of overfitting on narrow channel representations without explicit regularizing penalties.

This substantiates a fundamental engineering guideline: "A novel architecture is simply a prior model augmented with an inductive mechanism targeted at a concrete operational defect." Architectural add-ons yield measurable value only when the network encounters the precise computational bottleneck they are engineered to resolve; otherwise, they impose unnecessary computational and parameter overhead.
""")

    if d6 or d7:
        parts.append("""### LeNet-5 (LeCun et al., 1998)

The classical LeNet-5 architecture evaluated across both vision benchmarks in parallel with the baseline models. The network preserves LeCun's canonical feature mapping (6 then 16 feature maps with 5x5 kernels, connected to a 120 -> 84 -> 10 dense head), modernized using ReLU activations and Max Pooling to ensure algorithmic parity with `scratch_nn.py`.
""")
        for payload, title in ((d6, "MNIST — LeNet-5"), (d7, "CIFAR-10 — LeNet-5")):
            if not payload:
                continue
            parts.append(f"#### {title}\n")
            parts.append(_table(
                _rows(payload),
                ["framework", "dataset", "n_params", "epochs", "train_seconds",
                 "test_accuracy", "f1_macro"],
                ["Framework", "Dataset", "Params", "Epochs", "Train (s)", "Accuracy", "Macro F1"],
            ))
            parts.append("")
        parts.append("""One architecture applied to two datasets of matching spatial resolution (32x32) yields diametrically opposite outcomes. On MNIST, LeNet-5 excels on the problem domain for which it was originally engineered. On CIFAR-10, color photography introduces complex object variations where ~62k parameters — and specifically under 3k parameters within the convolutional feature extractor — prove inadequate to encode rich visual representations. Capacity must match empirical complexity.

Detailed comparative analyses are documented in `pdf/08_lenet_mnist_report.pdf` and `pdf/09_lenet_cifar10_report.pdf`.
""")

    # ---- parameter agreement ----
    agree = []
    for payload, name in ((d1, "Diabetes"), (d2, "MNIST"), (d3, "CIFAR-10"),
                          (d6, "MNIST (LeNet-5)"), (d7, "CIFAR-10 (LeNet-5)")):
        if not payload:
            continue
        counts = {r["n_params"] for r in _rows(payload)}
        agree.append(f"- **{name}**: {next(iter(counts)):,} parameters"
                     f" — {'all three frameworks agree' if len(counts) == 1 else 'MISMATCH: ' + str(counts)}")
    if agree:
        parts.append("\n## Parameter Verification\n")
        parts.append("Analytically calculated prior to implementation using tutorial section 43 formulas, then verified across all frameworks:\n")
        parts.append("\n".join(agree))

    parts.append("""

## Saved Models & Artifacts

All notebooks serialize trained networks alongside performance summaries. Weights are preserved natively under `results/models/<notebook>/` accompanied by JSON metadata sidecars detailing architecture, parameter totals, and validation scores:

| Framework Leg | Format | Self-Contained Graph? |
|---|---|---|
| Scratch (NumPy) | `.npz` — compressed array per parameter tensor | no (requires class instance) |
| TensorFlow/Keras | `.keras` — graph topology and trained weights | **yes** |
| PyTorch | `.pt` — `state_dict` weight mapping | no (requires class instance) |

```python
import ass4_utils as U

U.list_models()                                   # inspect all serialized weights
U.list_models("06_mnist_lenet")                   # filter by notebook directory

keras_model = U.load_model("lenet5_keras_subset", "06_mnist_lenet")       # standalone reload
torch_model = U.load_model("lenet5_torch_subset", "06_mnist_lenet",
                           model=LeNet5(C, N_CLASSES))                    # loads into fresh instance
```

Model weights are version-controlled in the repository, enabling instantaneous reloading and inference verification without re-training. The M1..M4 cache in `results/variant_cache/` can be refreshed on demand via `python prefill_variants.py`.

## Core Analytical Findings

**1. Architectural equivalence transcends software frameworks.** Across three benchmark datasets and diverse network topologies, NumPy, Keras, and PyTorch exhibited identical parameter counts, exact layer-by-layer tensor dimensions, and test classification metrics within statistical seed variance. `S.Dense`, `keras.layers.Dense`, and `nn.Linear` compute functionally indistinguishable mathematical operations.

**2. Abstraction alters inspection capability rather than computational mechanics.** The native NumPy implementation exposes each phase of the `Forward -> Loss -> Gradient -> Update` pipeline to explicit examination, with hand-coded analytical gradients checked against central finite differences. Keras concentrates execution within an opaque `fit()` call, whereas PyTorch offers a modular imperative loop driven by dynamic autograd.

**3. Hardware execution efficiency is intrinsically workload-dependent.** For lightweight tabular MLPs, PCI-e data marshaling and CUDA kernel launch latencies render PyTorch GPU execution slower than optimized CPU NumPy. On multi-channel spatial convolutions, highly parallelized GPU tensor cores dominate, drastically reversing runtime efficiency.

**4. Inductive bias must faithfully mirror intrinsic data topology.** Tabular features exhibit no canonical spatial ordering, making fully connected MLPs the natural choice. Image tensors possess spatial locality and shift invariance, providing rigorous theoretical justification for local receptive fields and weight sharing via CNNs.

## Methodological Limitations

- Constrained training budget (5 epochs on subsets, 10 epochs on channel-constrained 16/32/64 stages for M1..M4) devoid of data augmentation or adaptive learning rate schedulers.
- Single stochastic seed across mainline comparisons. As established in Notebook 04, initialization noise accounts for up to ~0.05 accuracy variation, demonstrating that cross-framework disparities reside within statistical noise.
- CUDA acceleration on desktop GPU (RTX 3060 12GB) paired with native FP32/AMP tensor execution.
- Clinical 30-day readmission prediction remains an inherently challenging tabular task; modest macro-F1 scores reflect acute class imbalance and clinical label noise rather than optimization shortcomings.

## Data Sources

- **Diabetes 130-US Hospitals**: UCI Machine Learning Repository, Dataset 296 — retrieved automatically into `data/`
- **MNIST & CIFAR-10**: Retrieved programmatically via `torchvision.datasets` into `data/`
""")

    return "\n".join(parts)


# Lines that are pure machinery noise: dataset-download progress bars and the
# logging banners TensorFlow/ZMQ emit at import. They carry no information about
# the experiments but can run to thousands of lines in an executed notebook.
_NOISE_MARKERS = (
    "kB/s]", "MB/s]", "it/s]", "B/s]",
    "oneDNN custom operations",
    "absl::InitializeLog",
    "TF_ENABLE_ONEDNN_OPTS",
    "Proactor event loop does not implement",
    "Kernel is running over TCP without encryption",
    "WARNING: All log messages before",
    "external/local_xla",
    "computation placer already registered",
)

_NOISE_PREFIX_RE = None


def _is_noise(line: str) -> bool:
    import re

    global _NOISE_PREFIX_RE
    if _NOISE_PREFIX_RE is None:
        # e.g. "  2%|          | 2.79M/170M [00:35<34:43, 80.5kB/s]"
        _NOISE_PREFIX_RE = re.compile(r"^\s*\d+%\|")
    s = line.strip()
    if not s:
        return False
    if _NOISE_PREFIX_RE.match(line):
        return True
    return any(mark in line for mark in _NOISE_MARKERS)


def clean_notebook_outputs(path: str) -> int:
    """Strip download progress bars and import banners from an executed notebook.

    Returns the number of output lines removed. Genuine stdout - training logs,
    tables, shapes, the TensorFlow "GPU not available" notice - is untouched.
    """
    with open(path, encoding="utf-8") as f:
        nb = json.load(f)

    removed = 0
    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        kept_outputs = []
        for out in cell.get("outputs", []):
            if out.get("output_type") != "stream":
                kept_outputs.append(out)
                continue

            text = out.get("text")
            lines = text if isinstance(text, list) else [text or ""]
            kept = [ln for ln in lines if not _is_noise(ln)]
            removed += len(lines) - len(kept)

            if not any(ln.strip() for ln in kept):
                continue            # output was nothing but noise
            out["text"] = kept
            kept_outputs.append(out)
        cell["outputs"] = kept_outputs

    with open(path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)
    return removed


def export_pdfs(names):
    """Notebook -> self-contained HTML -> PDF via Playwright/Chromium.

    `nbconvert --to webpdf` cannot be used here: on Windows it installs a
    SelectorEventLoop, which has no subprocess support, so launching Chromium
    dies with NotImplementedError. Driving Playwright's *sync* API ourselves
    sidesteps the event loop entirely. Neither pandoc nor LaTeX is involved.
    """
    ok, failed = [], []
    edge_path = r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
    html_dir = os.path.join(HERE, "_html")
    os.makedirs(html_dir, exist_ok=True)
    pdf_dir = os.path.join(HERE, "pdf")
    os.makedirs(pdf_dir, exist_ok=True)

    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            try:
                for name in names:
                    src = os.path.join(HERE, f"{name}.ipynb")
                    if not os.path.exists(src):
                        print(f"skip {name}: notebook missing")
                        continue

                    n_removed = clean_notebook_outputs(src)
                    print(f"exporting {name}.pdf "
                          f"({n_removed:,} noise lines stripped) ...", flush=True)
                    proc = subprocess.run(
                        [sys.executable, "-m", "nbconvert", "--to", "html",
                         "--embed-images", "--output-dir", html_dir, src],
                        capture_output=True, text=True,
                    )
                    html = os.path.join(html_dir, f"{name}.html")
                    if proc.returncode != 0 or not os.path.exists(html):
                        failed.append((name, (proc.stderr or proc.stdout or "")[-400:]))
                        continue

                    try:
                        page = browser.new_page()
                        page.goto("file:///" + html.replace("\\", "/"),
                                  wait_until="networkidle", timeout=180_000)
                        page.add_style_tag(content="""
                            pre, code, .jp-OutputArea-output, .highlight pre {
                                white-space: pre-wrap !important;
                                word-break: break-word !important;
                                overflow-wrap: anywhere !important;
                            }
                            .jp-Cell, .jp-OutputArea-child, table, tr, img {
                                break-inside: avoid;
                                page-break-inside: avoid;
                            }
                            img, svg { max-width: 100% !important; height: auto !important; }
                        """)
                        page.pdf(
                            path=os.path.join(pdf_dir, f"{name}.pdf"),
                            format="A4",
                            print_background=True,
                            margin={"top": "14mm", "bottom": "14mm",
                                    "left": "10mm", "right": "10mm"},
                        )
                        page.close()
                        ok.append(name)
                    except Exception as e:
                        failed.append((name, f"{type(e).__name__}: {e}"[:400]))
            finally:
                browser.close()
    except (ImportError, Exception) as e:
        if not os.path.exists(edge_path):
            raise RuntimeError(f"Neither Playwright nor Edge found: {e}")
        for name in names:
            src = os.path.join(HERE, f"{name}.ipynb")
            if not os.path.exists(src):
                print(f"skip {name}: notebook missing")
                continue

            n_removed = clean_notebook_outputs(src)
            print(f"exporting {name}.pdf via Edge "
                  f"({n_removed:,} noise lines stripped) ...", flush=True)
            proc = subprocess.run(
                [sys.executable, "-m", "nbconvert", "--to", "html",
                 "--embed-images", "--output-dir", html_dir, src],
                capture_output=True, text=True,
            )
            html = os.path.join(html_dir, f"{name}.html")
            if proc.returncode != 0 or not os.path.exists(html):
                failed.append((name, (proc.stderr or proc.stdout or "")[-400:]))
                continue

            pdf_path = os.path.join(pdf_dir, f"{name}.pdf")
            file_url = "file:///" + html.replace("\\", "/")
            cmd = [edge_path, "--headless=new", "--disable-gpu", f"--print-to-pdf={pdf_path}", file_url]
            res = subprocess.run(cmd, capture_output=True)
            if os.path.exists(pdf_path):
                ok.append(name)
            else:
                failed.append((name, res.stderr.decode("utf-8", errors="ignore")[-400:]))

    return ok, failed


if __name__ == "__main__":
    readme = build_readme()
    with open(os.path.join(HERE, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)
    print(f"wrote README.md ({len(readme):,} chars)")

    if "--no-pdf" not in sys.argv:
        ok, failed = export_pdfs([n for n, _ in NOTEBOOKS])
        print(f"\nPDFs written: {', '.join(ok) if ok else 'none'}")
        for name, err in failed:
            print(f"FAILED {name}:\n{err}\n")
